### ISSUE TITLE
Expansion to battery use

### ISSUE THREAD

**Issue by sheppy99** [transistorgrab/OSSI#2]
Is it worth expanding your project at some stage to include use with batteries? I'm thinking some sort of monitored situation whereby assuming the battery has sufficient charge, and assuming there is import electricity, that the inverter supplies just enough output if headroom is available to reduce the import to  a few watts. It could use a feed from Open Energy Monitor or similar to provide the instantaneous import / export power information.
In many parts of the world exported energy is something to be avoided, and importing is expensive

**Comment by transistorgrab** [comment]
Yes. There is no principal obstacle to use batteries as an input source.
It's one of the use cases. You only need to adjust the input voltage range to not drain the battery too low and also you have to disable the "Maximum Power Point" algorithm. This is "only" a software issue. Nothing that the hardware does not support.
For communication a UART (serial) port is provided in the design, usable for debug or other uses.

**Comment by sheppy99** [comment]
Thanks for the reply, will it be possible to vary the output of the inverter so generated power matches used power? I guess several inverters could be built as a lower power design and switched as needed but that seems a little inelegant. Also does the low voltage allow for the habit that Lithium batteries have of increasing their voltage once the load has been removed despite being almost empty. If it doesn't the inverter will cycle a lot whilst decreasing battery life

**Comment by transistorgrab** [comment]
The first can also be achieved via communication and setting a current limit. But this would require an external device that monitors energy flow from and to the grid. I think most of the energy flow control intelligence then needs to be placed in that device, since I fear that would exceed the computing power of the main controller.
The second could be achieved in the software that keeps track of the state of charge of the battery. but it depends on what kind of Lithium battery is in use. You need definitely a battery pack with a battery management system (BMS). (The inverter can not track all cells of a battery pack.)
The BMS (at least those I know) keep track of the state of charge of the battery. It remains to implement a communication interface to the battery/BMS. Some use CAN, I think there are also some that use other serial interfaces.
My opinion is, that lithium batteries are quite complicated in handling and operation. Therefore at least in the first iteration of the inverter only lead batteries can be used (no additional communication required, only cut off voltage must be respected).

**Comment by sheppy99** [comment]
I wonder if the inverter could take something like a MQTT message to tell it how much power to output? That could be generated by an energy monitoring system such as Open Energy Monitor, with an automation system such as Openhab stacked on top. If the inverter sent out its status, decisions could be made on both power demand and charge remaining and the requested power output could be modified in light of reported input voltage. 
The automation system can take control of what the inverter is asked to do, with the inverter maybe going into a failsafe mode if it hasn't received a valid message for a period of time.
Obviously a BMS is very important for both safety and longevity!

**Comment by transistorgrab** [comment]
Seems possible, just depends on how much overhead the communication protocol generates. It may be necessary to have a gateway that translates "inverter protocol" to "(home) automation protocol".
On the other hand if there is a light weight protocol freely available this could be implemented as the standard protocol for the inverter communication.
For example Modbus could be used ([freemodbus.org](http://www.freemodbus.org/)) but I don't know about the specifics.
